### ISSUE TITLE
Possible documentation issue with Provider property group example - doesn't render

### ISSUE THREAD

**Issue by misterspeedy** [geodanila/Feliz.ReactSpectrum#1]
In the documentation here:

https://geodanila.github.io/Feliz.ReactSpectrum/#/provider

...the property group example doesn't render anything visible unless you add 

    Provider.defaultTheme   

...in the Provider definition.

Not sure if this is a documentation issue or a code issue.

**Comment by geodanila** [comment]
Hi Kit,

First of all - I loved your "F# from the ground up" course.

That particular example already assumes you're using the Provider component in the root of your application for themeing. It's just used for controlling common properties for multiple child components - in that case for controlling the isDisabled prop.

Would be a good idea to specify this in the documentation.

**Comment by misterspeedy** [comment]
Ah thank you!  I did guess that might be the case but didn't try it.

Very pleased you liked the course - that has made my day.

In return I must say, we are very, very excited by what you have done with Feliz.ReactSpectrum!

**Comment by geodanila** [comment]
That is great to hear, coming from you! 

I've loved F# since the day I first heard of it and I've been meaning to start contributing to the F# open source community for quite a while. The reception has been great, thank you!

**Comment by misterspeedy** [comment]
Well you certainly hit the ground running!

**Comment by geodanila** [comment]
9053e66 - added a small comment to clarify the need for a separate root-level Provider. 

Thanks for the feedback. 

Closing the issue.
